In [3]:
#def function
def saumya(name,place,age=18):
    print(name)
    print(place)
    print(age)
    
saumya("deep","khowai",20)    
    

deep
khowai
20


In [6]:
def sigmoid(x):
    e=2.732
    y=1/1+e**(-x)
    return y
sigmoid(32)

1.0000000000000109

In [1]:
# class & objects
class cricket:
    def __init__(self,name,age):
        self.name=name
        self.age=age
        
saumya=cricket("deep",20)    #here "saumya" is the object & cricket is the class.
print(saumya.name)


deep


In [4]:
l=["deep","rahul","tukan","joy"]
for i in l :
    if i=="deep":
        print(i*2)
    else :
        print("bad"*3)

    
     

deepdeep
badbadbad
badbadbad
badbadbad


In [6]:
i=0
for i in range (10):
    print(i)
    
print(5+5)    

0
1
2
3
4
5
6
7
8
9
10


In [7]:
import numpy as np 
import pandas as pd
import scipy 
import random

df=pd.DataFrame(np.random.rand(5,5), index=['a','b','c','d','e'], columns=['1','2','3','4','5'])
print(df)

          1         2         3         4         5
a  0.239781  0.122927  0.150462  0.068357  0.536644
b  0.002573  0.739686  0.861311  0.305352  0.643857
c  0.358896  0.938203  0.906342  0.460802  0.861425
d  0.021238  0.474419  0.728262  0.919204  0.313128
e  0.362388  0.484770  0.070940  0.630871  0.141464


In [8]:
df.iloc[2,4]

0.8614252363719038

In [9]:
df.loc["d","4"]

0.919203931430499

In [10]:
df.drop(['a'])

1         2         3         4         5
b  0.002573  0.739686  0.861311  0.305352  0.643857
c  0.358896  0.938203  0.906342  0.460802  0.861425
d  0.021238  0.474419  0.728262  0.919204  0.313128
e  0.362388  0.484770  0.070940  0.630871  0.141464

In [11]:
print(df)

          1         2         3         4         5
a  0.239781  0.122927  0.150462  0.068357  0.536644
b  0.002573  0.739686  0.861311  0.305352  0.643857
c  0.358896  0.938203  0.906342  0.460802  0.861425
d  0.021238  0.474419  0.728262  0.919204  0.313128
e  0.362388  0.484770  0.070940  0.630871  0.141464


In [16]:
df.drop(['b'],inplace=True)
print(df)

          1         2         3         4         5
c  0.358896  0.938203  0.906342  0.460802  0.861425
d  0.021238  0.474419  0.728262  0.919204  0.313128
e  0.362388  0.484770  0.070940  0.630871  0.141464


In [17]:
print(df)

          1         2         3         4         5
c  0.358896  0.938203  0.906342  0.460802  0.861425
d  0.021238  0.474419  0.728262  0.919204  0.313128
e  0.362388  0.484770  0.070940  0.630871  0.141464


In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr1=np.array([[2,5,9],[5,6,8],[7,3,4]])
print(arr1)

[[2 5 9]
 [5 6 8]
 [7 3 4]]


In [23]:
print(arr+arr1)
print(arr*arr1)

[[ 3  7 12]
 [ 9 11 14]
 [14 11 13]]
[[ 2 10 27]
 [20 30 48]
 [49 24 36]]


In [42]:
class gogo:
    def __init__(self,duck=5,punch=5,jump=5,rightmove=5,leftmove=5):  
        self.duck=duck
        self.punch=punch
        self.jump=jump
        self.rightmove=rightmove
        self.leftmove=leftmove
        
        
gogoman=gogo(5,5,4)  # here all activities of gogoman record & executes.
print(gogoman.leftmove)

gogo_women=gogo(1,5,8) # here all activities of gogo_women records & executes.
print(gogo_women.jump)


5
8


In [ ]:
class obstacle:
    def__init__(self,size=0.5,shape=0.7,impact=0)
    self.size=size
    self.shape=shape
    self.impact=impact
    
    if self.size>= 0.6:
        print